user_agent_class.user_agent_entity.*:
  type: config_entity
  label: 'User agent entity config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    class:
      type: string
      label: 'Class'
    enableCheck:
      type: boolean
      label: 'EnableCheck'
    exclude:
      type: string
      label: 'Exclude'
    uuid:
      type: string
