odata_client.odata_server.*:
  type: config_entity
  label: 'Odata server config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    url:
      type: string
      label: 'Url'
    authentication_method:
      label: 'Authentication method'
      none:
        type: string
      basic:
        type: string
      oauth:
        type: string
    client_id:
      type: string
      label: 'Client id'
    client_secret:
      type: string
      label: 'Client secret'
    redirect_uri:
      type: string
      label: 'Redirect uri'
    url_authorize:
      type: string
      label: 'Authorize url'
    url_access_token:
      type: string
      label: 'Url access token'
    token_provider:
      type: string
      label: 'Access token provider'
    tenant:
      type: string
      label: 'The azure client id (tenant)'
    url_resource_owner_details:
      type: string
      label: 'Url resource owner details'
    user_name:
      type: string
      label: 'User name'
    password:
      type: string
      label: 'Password'
    odata_type:
      type: string
      label: 'Odata type'
    default_collection:
      type: string
      label: 'Default collection'
